.TH tater 1 2023-01-16

.SH NAME
tater \- simple scripting language for tot lovers

.SH SYNOPSIS
.B tater
[\fIOPTION\fR]... [\fIFILE\fR]
.LP
.B options:
\fB-d\fR,
\fB-s\fR,
\fB-t\fR,
\fB-h\fR,
\fB-v\fR,
.LP

.SH DESCRIPTION
.B tater
is a simple scripting language based upon the excellent work of Robert Nystrom.

If a file is note passed on the command line the \fBREPL\fR will be started.

.SH OPTIONS
.TP
\fB\-d\fR
Enable debug mode
.TP
\fB\-s\fR
Garbage collection stress mode
.TP
\fB\-t\fR
Garbage collection tracing
.TP
\fB\-h\fR
Help
.TP
\fB\-v\fR
Version and license information

.SH NOTES
.PP
\fBtater\fR is \fBALPHA\fR quality.

.SH AUTHOR
Jason Woodward <woodwardj@jaos.org>
